Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('motorControl', src, depend = [''], CPPPATH = CPPPATH)

Return('group')


#https://github.com/BoschSensortec